name: photolandapp
description: "PhotoLand Studio Management App"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  # Flutter Localizations (برای DatePicker و dialog ها)
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.0.0
  cloud_firestore: ^5.4.4

  cloud_functions: ^5.0.0

  # State Management
  provider: ^6.1.1

  path_provider: ^2.1.4

  go_router: ^14.0.0

  pdf: ^3.10.4
  printing: ^5.11.0

  # تقویم شمسی
  shamsi_date: ^1.0.1
  persian_datetime_picker: ^3.1.1

  # UI
  cupertino_icons: ^1.0.8

  # Utilities
  url_launcher: ^6.3.1
  share_plus: ^10.1.2
  intl: ^0.20.2
  flutter_svg: ^2.2.1
  font_awesome_flutter: ^10.12.0

  # برای انتخاب عکس
  image_picker: ^1.0.7

  animations: ^2.0.11

  # برای QR Code
  qr_flutter: ^4.1.0

  # برای هش SHA-256
  crypto: ^3.0.7

  flutter_local_notifications: ^19.5.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: 'Vazirmatn'
      fonts:
        - asset: fonts/Vazirmatn-Regular.ttf



flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#fff"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"  # اختیاری